ARG ZAP_VERSION
ARG DOCKERHUB=dockerhub.tax.service.gov.uk
FROM dockerhub.tax.service.gov.uk/zaproxy/zap-stable:${ZAP_VERSION}

ENV ZAP_STORAGE_SESSIONS_HOST="artefacts.tax.service.gov.uk"
ENV ZAP_STORAGE_SESSIONS_API_KEY=""
ENV ZAP_BUNDLE="current"
ENV ZAP_HOME=/home/zap/.ZAP
ENV ZAP_PORT=11000
ENV ZAP_FORWARD_ENABLE="false"

USER root

RUN sed -i 's|http:|https:|g' /etc/apt/sources.list.d/debian.sources

# Minimal fix: ldconfig workaround for ARM64 segmentation fault
RUN set -eux; \
    echo 'Acquire::https::Verify-Peer "false";' >/etc/apt/apt.conf.d/80-ignore-tls; \
    apt-get update; \
    arch="$(uname -m)"; \
    if [ "${arch}" = "aarch64" ] || [ "${arch}" = "arm64" ]; then \
        dpkg-divert --add --rename --divert /sbin/ldconfig.real /sbin/ldconfig; \
        printf '#!/bin/sh\nexit 0\n' >/sbin/ldconfig; \
        chmod +x /sbin/ldconfig; \
    fi; \
    DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates; \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
        jq=1.6* \
        rinetd=0.73*; \
    if [ -f /sbin/ldconfig.real ]; then \
        rm /sbin/ldconfig; \
        dpkg-divert --rename --remove /sbin/ldconfig; \
    fi; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*; \
    touch /var/run/rinetd.pid; \
    chown zap:zap /var/run/rinetd.pid; \
    rm -f /etc/apt/apt.conf.d/80-ignore-tls

USER zap

# Autogenerated by updater.py - DO NOT EDIT MANUALLY
WORKDIR /zap/plugin
ARG ASCANRULES_VERSION=83
ARG ASCANRULESBETA_VERSION=66
ARG PSCANRULES_VERSION=75
ARG PSCANRULESBETA_VERSION=50
ARG RETIRE_VERSION=0.66.0
ARG ALERTFILTERS_VERSION=27
ARG COMMONLIB_VERSION=1.44.0
ARG NETWORK_VERSION=0.29.0
ARG OAST_VERSION=0.26.0
ARG DATABASE_VERSION=0.9.0
ARG NETWORK_VERSION=0.29.0
ARG PSCAN_VERSION=0.6.0
ARG COMMONLIB_VERSION=1.44.0
RUN rm --force \
        ascanrules-release-*.zap \
        ascanrulesBeta-beta-*.zap \
        pscanrules-release-*.zap \
        pscanrulesBeta-beta-*.zap \
        retire-release-*.zap \
        alertFilters-release-*.zap \
        commonlib-release-*.zap \
        network-beta-*.zap \
        oast-beta-*.zap \
        database-alpha-*.zap \
        network-beta-*.zap \
        pscan-alpha-*.zap \
        commonlib-release-*.zap \
    && wget --quiet \
        https://github.com/zaproxy/zap-extensions/releases/download/ascanrules-v${ASCANRULES_VERSION}/ascanrules-release-${ASCANRULES_VERSION}.zap \
        https://github.com/zaproxy/zap-extensions/releases/download/ascanrulesBeta-v${ASCANRULESBETA_VERSION}/ascanrulesBeta-beta-${ASCANRULESBETA_VERSION}.zap \
        https://github.com/zaproxy/zap-extensions/releases/download/pscanrules-v${PSCANRULES_VERSION}/pscanrules-release-${PSCANRULES_VERSION}.zap \
        https://github.com/zaproxy/zap-extensions/releases/download/pscanrulesBeta-v${PSCANRULESBETA_VERSION}/pscanrulesBeta-beta-${PSCANRULESBETA_VERSION}.zap \
        https://github.com/zaproxy/zap-extensions/releases/download/retire-v${RETIRE_VERSION}/retire-release-${RETIRE_VERSION}.zap \
        https://github.com/zaproxy/zap-extensions/releases/download/alertFilters-v${ALERTFILTERS_VERSION}/alertFilters-release-${ALERTFILTERS_VERSION}.zap \
        https://github.com/zaproxy/zap-extensions/releases/download/commonlib-v${COMMONLIB_VERSION}/commonlib-release-${COMMONLIB_VERSION}.zap \
        https://github.com/zaproxy/zap-extensions/releases/download/network-v${NETWORK_VERSION}/network-beta-${NETWORK_VERSION}.zap \
        https://github.com/zaproxy/zap-extensions/releases/download/oast-v${OAST_VERSION}/oast-beta-${OAST_VERSION}.zap \
        https://github.com/zaproxy/zap-extensions/releases/download/database-v${DATABASE_VERSION}/database-alpha-${DATABASE_VERSION}.zap \
        https://github.com/zaproxy/zap-extensions/releases/download/network-v${NETWORK_VERSION}/network-beta-${NETWORK_VERSION}.zap \
        https://github.com/zaproxy/zap-extensions/releases/download/pscan-v${PSCAN_VERSION}/pscan-alpha-${PSCAN_VERSION}.zap \
        https://github.com/zaproxy/zap-extensions/releases/download/commonlib-v${COMMONLIB_VERSION}/commonlib-release-${COMMONLIB_VERSION}.zap
# Autogenerated END

COPY --chown=zap:zap zap /zap

CMD ["/zap/zapw.sh"]
