ARG ZAP_VERSION
FROM owasp/zap2docker-stable:${ZAP_VERSION}

ENV ZAP_STORAGE_SESSIONS_HOST="artefacts.tax.service.gov.uk"
ENV ZAP_STORAGE_SESSIONS_API_KEY=""
ENV ZAP_BUNDLE="current"
ENV ZAP_HOME=/home/zap/.ZAP
ENV ZAP_PORT=11000

USER root

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    jq=1.5* \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER zap

# Autogenerated by updater.py - DO NOT EDIT MANUALLY
# Autogenerated END

COPY --chown=zap:zap docker/teardown /zap/teardown
COPY --chown=zap:zap docker/zapw.sh /zap/zapw.sh

CMD ["/zap/zapw.sh"]
